# Generated by Django 5.2.17 on 2026-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_videocallbooking_wizard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocallbooking',
            name='booking_type',
            field=models.CharField(choices=[('video_call', 'Video call'), ('appointment', 'Appointment')], default='video_call', max_length=20),
        ),
        migrations.AddField(
            model_name='videocallbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocallbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
