# Generated by Django 5.2.17 on 2026-09-08 11:00

import inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_videocallbooking_booking_type_videocallbooking_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='product_interest',
            field=models.CharField(blank=True, choices=inquiries.models.product_interest_choices, max_length=30),
        ),
    ]
