# Generated by Django 5.2.17 on 2026-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_contactsubmission_product_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('stage', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('ordered', 'Ordered'), ('repeat', 'Repeat Customer')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
