# Generated by Django 5.2.17 on 2026-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_slug_remove_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='default_moq',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
