# Generated by Django 5.2.17 on 2026-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_collection_default_moq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='collection',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
